services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8080:8000"

#  caddy:
#    image: caddy:latest
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#     - "8000:8000"
#    volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile
#       - caddy_data:/data
#       - caddy_config:/config
#       # Caddy needs access to the static CSS files to serve them
#     - .:/app 
#    depends_on:
#      - web

#volumes:
#  caddy_data:
#  caddy_config:
