services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8080:80"   # The side door for Staging!
      # - "443:443" # Commented out to prevent conflicts with Production SSL
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - .:/app 
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config: