# Generated by Django 5.2.14 on 2026-05-19 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squat_1rm', models.IntegerField(default=0, help_text='Current Squat Max')),
                ('bench_1rm', models.IntegerField(default=0, help_text='Current Bench Max')),
                ('deadlift_1rm', models.IntegerField(default=0, help_text='Current Deadlift Max')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
