# Generated by Django 5.2.14 on 2026-05-20 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text="General session notes (e.g., 'Felt sluggish', 'Slept poor')", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('SQUAT', 'Squat'), ('BENCH', 'Bench Press'), ('DEADLIFT', 'Deadlift')], max_length=20)),
                ('weight', models.IntegerField(help_text='Weight in lbs')),
                ('reps', models.IntegerField()),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, help_text='Rate of Perceived Exertion (1-10)', max_digits=3, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='lifting.workoutsession')),
            ],
        ),
    ]
