# Generated by Django 5.2.14 on 2026-05-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0002_workoutsession_workoutset'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='e1rm',
            field=models.IntegerField(blank=True, help_text='Estimated 1RM calculated via Epley formula', null=True),
        ),
    ]
