# Generated by Django 5.2.14 on 2026-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0003_workoutset_e1rm'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='is_warmup',
            field=models.BooleanField(default=False),
        ),
    ]
