# Generated by Django 5.2.14 on 2026-05-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0004_workoutset_is_warmup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutset',
            name='is_warmup',
        ),
    ]
