# Generated by Django 5.2.14 on 2026-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0005_remove_workoutset_is_warmup'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='set_type',
            field=models.CharField(choices=[('warmup', 'Warm Up'), ('working', 'Working'), ('failure', 'Failure')], default='working', max_length=10),
        ),
    ]
