# Generated by Django 6.0.5 on 2026-05-30 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0006_workoutset_set_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
