# Generated by Django 6.0.5 on 2026-05-30 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0007_alter_workoutsession_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lifterprofile',
            name='body_weight',
            field=models.DecimalField(decimal_places=1, default=180.0, help_text='Current body weight in lbs', max_digits=5),
        ),
        migrations.AddField(
            model_name='lifterprofile',
            name='formula_preference',
            field=models.CharField(choices=[('epley', 'Epley'), ('brzycki', 'Brzycki'), ('lander', 'Lander')], default='epley', help_text='Formula used to calculate estimated 1RM', max_length=15),
        ),
        migrations.AddField(
            model_name='lifterprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text='Gender for relative strength scaling', max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='e1rm',
            field=models.IntegerField(blank=True, help_text='Estimated 1RM calculated via preferred formula', null=True),
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Routine Name (e.g. 'Push Day A')", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('SQUAT', 'Squat'), ('BENCH', 'Bench Press'), ('DEADLIFT', 'Deadlift')], max_length=20)),
                ('weight', models.IntegerField(help_text='Target weight in lbs')),
                ('reps', models.IntegerField()),
                ('set_type', models.CharField(choices=[('warmup', 'Warm Up'), ('working', 'Working'), ('failure', 'Failure')], default='working', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lifting.workouttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
