# Generated by Django 6.0.5 on 2026-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0008_lifterprofile_body_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifterprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('other', 'Other / Prefer Not to Say')], default='male', help_text='Gender identity for profile and relative strength scaling', max_length=15),
        ),
    ]
