# Generated by Django 6.0.5 on 2026-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0009_alter_lifterprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifterprofile',
            name='show_rest_timer',
            field=models.BooleanField(default=True, help_text='Automatically pop up the rest timer when a set is logged'),
        ),
    ]
