# Generated by Django 6.0.5 on 2026-05-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0010_lifterprofile_show_rest_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifterprofile',
            name='weight_unit',
            field=models.CharField(choices=[('lbs', 'Lbs'), ('kg', 'Kg')], default='lbs', help_text='Preferred weight unit across the application', max_length=5),
        ),
    ]
